### ISSUE TITLE
SLU08: Classification with Logistic Regression

### ISSUE THREAD

**Issue by rodrigomverissimo** [LDSSA/batch3-portal-support#1]
**Name**
SLU08: Classification with Logistic Regression

**Description**
- Practical Introduction to Classification
- Classification with Logistic Regression
- Using Logistic Regression

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Rodrigo Veríssimo

**Due date**
22nd June

**Comment by hcastilho** [comment]
Hi Rodrigo
I've added you to the portal whitelist, could you visit it so your user is created?
https://portal.lisbondatascience.org/

Thanks!

**Comment by rodrigomverissimo** [comment]
Hi @hcastilho 
It works! Thanks!

![hacker-voice-im-in-9461453](https://user-images.githubusercontent.com/14314975/59568582-72e92980-9074-11e9-928c-d5a48bdc845f.png)

**Comment by hcastilho** [comment]
Done
