### ISSUE TITLE
SLU18 - Hyperparameter Tuning

### ISSUE THREAD

**Issue by Luisfandrade** [LDSSA/batch3-portal-support#10]
**Name**
SLU18 - Hyperparameter Tuning

**Description**
This learning unit covers Hyperparameter tuning including the definition of hyperparameters, how to select them, how to validate them, and how to select the best model based on them. 

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Luis Andrade (luis.andrade.93@gmail.com)

**Due date**
07/07/2019

**Comment by hcastilho** [comment]
Created
