### ISSUE TITLE
SLU18 - Workflow

### ISSUE THREAD

**Issue by hershaw** [LDSSA/batch3-portal-support#12]
**Name**
Workflow

**Description**
This is a learning unit that is mostly just a presentation of best practices and workflow steps. It is meant to act more as a reference than as something that teaches technical tools.

**Specialization**
S19 - Workflow

**Main contact for the learning unit**
Sam Hopkins

**Due date**
22 June

**Comment by hcastilho** [comment]
Hi,
I already have a SLU18 registered with Hyperparameter Tuning.
Which one is correct?
