### ISSUE TITLE
SLU03 - Data Visualization

### ISSUE THREAD

**Issue by manugarri** [LDSSA/batch3-portal-support#15]
**Name**
Data Visualization

**Description**
How to use data visualization to find patterns in data and communicate an idea effectively

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Manuel Garrido

**Due date**
22 June

**Comment by hcastilho** [comment]
Could you go to the portal so your user gets created?
https://portal.lisbondatascience.org/
