### ISSUE TITLE
SLU01: Pandas 101

### ISSUE THREAD

**Issue by FilipaRodrigues** [LDSSA/batch3-portal-support#2]
**Name**
SLU01 - Pandas 101

**Description**
- Importing Pandas
- Series and Dataframes
- Previewing a Dataframe
- Retrieving Dataframe information
- Reading/Writing data

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Filipa Rodrigues

**Due date**
22nd June

**Comment by hcastilho** [comment]
I've added you the the portal whitelist.
Please log in the portal so your user is created and I can set it as the contact.
https://portal.lisbondatascience.org/

**Comment by hcastilho** [comment]
Done
