### ISSUE TITLE
BLU02 - Advanced Wrangling

### ISSUE THREAD

**Issue by ruimgf** [LDSSA/batch3-portal-support#20]
**Name**
BLU02 - Advanced Wrangling

**Description**
Some useful tools to handle datasets, group-apply-combine, create tidy datasets, Pipelines, and Feature Unions

**Specialization**
S02 - Data Wrangling

**Main contact for the learning unit**
Rui Figueiredo 

**Due date**
5th August 2019

**Comment by hcastilho** [comment]
Done
