### ISSUE TITLE
Register BLU03 -  Data Sources

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [LDSSA/batch3-portal-support#21]
**Name**
BLU03 -  Data Sources

**Description**
This BLU introduces three new data sources, and ways to extract data from them. The first one are SQL databases (basic concepts about databases are explained and the Structured Query Language is introduced). The second one are public APIs (introduces HTTP GET requests). The last one are web pages (introduces web scraping).

**Specialization**
S02 - Data Wrangling

**Main contact for the learning unit**
Frederico Nunes (FredericoCoelhoNunes)

**Due date**
August 24th

**Comment by hcastilho** [comment]
Done
