### ISSUE TITLE
Register BLU01 - Messy data

### ISSUE THREAD

**Issue by nunobbras** [LDSSA/batch3-portal-support#22]
**Name**
BLU01 - Messy data

**Description**
This learning unit is about common problems when handling alternative structured data files such as 
1) csv files with specific delimiters or corrupt data
2) non-csv formats, like excel with multiple sheets or json files. 

It covers unix based methods and pandas/python methods. It ends up with how to deal with large files, e.g., loading and reading csv's using chunks.

**Specialization**
S02 - Data Wrangling

**Main contact for the learning unit**
Nuno Brás (nunobbras)

**Due date**
July 29th

**Comment by hcastilho** [comment]
Done
