### ISSUE TITLE
SLU09: Model Selection & Overfitting

### ISSUE THREAD

**Issue by cmaroti** [LDSSA/batch3-portal-support#3]
**Name**
SLU09: Model Selection & Overfitting

**Description**
* Generalization Error
* Model Selection
* Regularized Linear Regression

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Christine Maroti

**Due date**
June 22

**Comment by hcastilho** [comment]
Hi Christine
I've added your github hande to the whitelist.
Can you go over to the portal please? https://portal.lisbondatascience.org/academy/student/units/
This will create your user so I can set it as the contact.

**Comment by hcastilho** [comment]
Thanks!
