### ISSUE TITLE
BLU10 - Non-Personalised RecSys

### ISSUE THREAD

**Issue by dominguezmaria** [LDSSA/batch3-portal-support#31]
**Name**
BLU10 - Non-Personalised RecSys

**Description**
1. Introduction to recommender systems
2. Ratings matrix, which is a sparse scipy matrix
3. Generic recommender systems.

**Specialization**
S05 - Recommender Systems

**Main contact for the learning unit**
Hugo Ferreira and Francisco Fonseca

**Due date**
23-11-2019

**Comment by hcastilho** [comment]
Done
