### ISSUE TITLE
SLU07: Regression with Linear Regression

### ISSUE THREAD

**Issue by CatarinaSilva** [LDSSA/batch3-portal-support#4]
**Name**
SLU07: Regression with Linear Regression

**Description**
Practical Introduction to Linear Regression
Training a Linear Regression
Using Linear Regression

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Catarina Silva

**Due date**
22nd June

**Comment by hcastilho** [comment]
Hi Catarina!
I've added you to the portal whitelist, could you visit it so your user is created?
https://portal.lisbondatascience.org/

Thanks

**Comment by CatarinaSilva** [comment]
Done @hcastilho
