### ISSUE TITLE
SLU10: Metrics for Regression

### ISSUE THREAD

**Issue by CatarinaSilva** [LDSSA/batch3-portal-support#5]
**Name**
SLU10: Metrics for Regression

**Description**
Loss Function vs. Evaluation Metric
Evaluation Metrics for Regression
Using the Metrics

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Catarina Silva

**Due date**
22nd June

**Comment by hcastilho** [comment]
Please see:
https://github.com/LDSSA/batch3-portal-support/issues/4#issuecomment-502387979

**Comment by CatarinaSilva** [comment]
Done @hcastilho
