### ISSUE TITLE
SLU02 - Subsetting data

### ISSUE THREAD

**Issue by aespedrosa** [LDSSA/batch3-portal-support#6]
Name
SLU02 - Subsetting data

Description
    - Setting pandas Dataframe index
    - Selecting columns (brackets and dot notation)
    - Selecting rows (loc and iloc)
    - Chain indexing (not good) vs Multi-axis indexing (good)
    - Masks
    - Where
    - Subsetting on conditions
    - Removing columns and rows
    - Adding columns and rows

Specialisation
S01 - Bootcamp and Binary Classification

Main contact for the learning unit
André Pedrosa

Due date
22nd June

**Comment by hcastilho** [comment]
Hi!
I've added you to the portal whitelist, could you visit it so your user is created?
https://portal.lisbondatascience.org/

Thanks
