### ISSUE TITLE
SLU15: Feature Engineering (aka Real World Data)

### ISSUE THREAD

**Issue by hugorcf** [LDSSA/batch3-portal-support#7]
**Name**
SLU15: Feature Engineering (aka Real World Data)

**Description**
Types of Statistical Data
Dealing with Numerical Features
Dealing with Categorical Features

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Hugo Ferreira

**Due date**
22 June

**Comment by hcastilho** [comment]
Hi!
I've added you to the portal whitelist, could you visit it so your user is created?
https://portal.lisbondatascience.org/

Thanks

**Comment by hugorcf** [comment]
I can confirm that the user has been created.

**Comment by hcastilho** [comment]
Created
