### ISSUE TITLE
SLU04: Basic Stats with Pandas

### ISSUE THREAD

**Issue by hugorcf** [LDSSA/batch3-portal-support#8]
**Name**
SLU04: Basic Stats with Pandas

**Description**
Descriptive Statistics
Inspecting Distributions
Outlier Detection

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Hugo Ferreira

**Due date**
22 June

**Comment by hcastilho** [comment]
See the comment I left on https://github.com/LDSSA/batch3-portal-support/issues/7

**Comment by hcastilho** [comment]
Created
