### ISSUE TITLE
SLU12 - Support Vector Machines

### ISSUE THREAD

**Issue by Luisfandrade** [LDSSA/batch3-portal-support#9]
**Name**
SLU12 - Support Vector Machines

**Description**
This SLU covers Support Vector machines including hyperplanes, the Maximal Margin Classifier, the Support Vector Classifier, the multi-class extension, and the Support Vector Regressor

**Specialization**
S01 - Bootcamp and Binary Classification

**Main contact for the learning unit**
Luis Andrade (luis.andrade.93@gmail.com)

**Due date**
07/07/2019

**Comment by hcastilho** [comment]
Please visit the portal and authenticate.
This will create a user so I can set you as the contact.

**Comment by Luisfandrade** [comment]
Hello Hugo,
Done.

**Comment by hcastilho** [comment]
Created
